import os
import sys
import math
from snakemake.utils import min_version

min_version("6.6")

SDIR = os.path.realpath(os.path.dirname(srcdir("Snakefile")))
shell.prefix(f"set -eo pipefail;")

mask_config = {"samples":{"FastCN":config["fasta"]}}


wildcard_constraints:
    sample="FastCN",


module Rhodonite:
    snakefile:
        "https://github.com/mrvollger/Rhodonite/raw/master/workflow/Snakefile"
    config:
        mask_config


# import the rules from Rhodonite
use rule * from Rhodonite as Rhodonite_*


rule all:
    input:
        expand("results/{sample}.bin", sample="FastCN"),


rule mask_file:
    input:
        rm=rules.Rhodonite_RepeatMasker.output.bed,
        trf=rules.Rhodonite_trf.output.bed,
        gaps=rules.Rhodonite_gaps.output.bed,
        fai=f'{config["fasta"]}.fai',
    output:
        bed="results/{sample}.mask.bed",
    shell:
        """
        cat {input.rm} {input.trf} {input.gaps} \
            | bedtools sort -i - -g {input.fai} \
            | bedtools slop -i - -g {input.fai} -b 36 \
            | bedtools merge -i - \
        > {output.bed}
        """


rule exclude_file:
    input:
        sd=config["sd"],
        wm=rules.Rhodonite_windowmasker.output.bed,
        fai=f'{config["fasta"]}.fai',
    output:
        bed="results/{sample}.exclude.bed",
    shell:
        """
        cat {input.wm} {input.sd} \
            | bedtools sort -i - -g {input.fai} \
            | bedtools merge -i - \
        > {output.bed}
        """


rule fastCN_GC_mask:
    input:
        mask=rules.mask_file.output.bed,
        exclude=rules.exclude_file.output.bed,
        fasta=config["fasta"],
        fai=f'{config["fasta"]}.fai',
    output:
        bin="results/{sample}.bin",
    shell:
        """
        export PATH=$PWD/fastCN:$PATH
        GC_control_gen \
            {input.fasta} \
            {input.exclude} \
            {input.mask} \
            400 \
            {output.bin} \
        """
