[project]
authors = ["Mitchell R. Vollger <mrvollger@gmail.com>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "fastcn-smk"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks]
fmt = "ruff format . && taplo format pixi.toml && snakefmt workflow/"
test = { cmd = [
  "snakemake",
  "-s",
  "$PIXI_PROJECT_ROOT/workflow/Snakefile",
  "--configfile",
  ".test/config.yaml",
  "-k",
] }
snakemake = { cmd = "cd $INIT_CWD && snakemake -s $PIXI_PROJECT_ROOT/workflow/Snakefile" }


[dependencies]
conda = "*"
snakemake = "==8.21"
snakefmt = "*"
ruff = "*"
taplo = "*"
snakemake-executor-plugin-slurm = "*"

#[target.linux-64.dependencies]
#apptainer = { channel = "conda-forge" }
